### ISSUE TITLE
Erro npm module

### ISSUE THREAD

**Issue by Anderson-Juhasc** [bitpay/bitcore-mnemonic#43]
$ node address.js 
/home/dragon/projects/bitcore/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
          ^
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/home/dragon/projects/bitcore/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/home/dragon/projects/bitcore/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/dragon/projects/bitcore/node_modules/bitcore-mnemonic/lib/mnemonic.js:3:15)
    at Module._compile (module.js:460:26)

**Comment by matiu** [comment]
More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.

**Comment by Anderson-Juhasc** [comment]
@matiuI recreated my package.json file, I was downloading the bitcore without -lib too.
